services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=alt0_Secreto
      - DB_NAME=armun
      - DB_PORT=3306
    volumes:
      - .:/app
      - ./init.sql:/app/init.sql

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: armun
      MYSQL_ROOT_PASSWORD: alt0_Secreto
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

