USE armun;

SET FOREIGN_KEY_CHECKS=0; 

TRUNCATE TABLE charlas;
TRUNCATE TABLE mocions;
TRUNCATE TABLE podios;
TRUNCATE TABLE premios;
TRUNCATE TABLE voluntarios;


TRUNCATE TABLE d_adjuntos;
TRUNCATE TABLE comites;
TRUNCATE TABLE delegados;
TRUNCATE TABLE directors;

TRUNCATE TABLE mesas;
TRUNCATE TABLE moderadors;
TRUNCATE TABLE pais;
TRUNCATE TABLE secretariados;

SET FOREIGN_KEY_CHECKS=1; 
