USE armun;

SET FOREIGN_KEY_CHECKS=0; 
TRUNCATE TABLE charlas;  
TRUNCATE TABLE comites;
TRUNCATE TABLE d_adjuntos;
TRUNCATE TABLE delegados;
TRUNCATE TABLE directors;
TRUNCATE TABLE mesas;
TRUNCATE TABLE mocions;
TRUNCATE TABLE moderadors;
TRUNCATE TABLE pais;
TRUNCATE TABLE podios;
TRUNCATE TABLE premios;
TRUNCATE TABLE secretariados;
TRUNCATE TABLE voluntarios;
SET FOREIGN_KEY_CHECKS=1;
